version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/autostageai/replicate-go"
  dependencies_vendored = true

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"